# Generated by Django 2.2.6 on 2022-12-08 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20221117_0636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='slug',
            field=models.SlugField(help_text='адрес', unique=True, verbose_name='уникальный адрес'),
        ),
    ]
